<a href="https://colab.research.google.com/github/Oluwapelumi-E/COHORT-3/blob/master/HPRACTICAL5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas import Timestamp
import warnings
import plotly.graph_objects as go
import plotly.offline as pyo
import plotly.io as pio
import sklearn
import plotly.express as ex
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('/content/supermart sales.csv')

In [3]:
data

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit,State
0,OD1,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,North,1254,0.12,401.28,Tamil Nadu
1,OD2,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,South,749,0.18,149.80,Tamil Nadu
2,OD3,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,West,2360,0.21,165.20,Tamil Nadu
3,OD4,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,South,896,0.25,89.60,Tamil Nadu
4,OD5,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,South,2355,0.26,918.45,Tamil Nadu
...,...,...,...,...,...,...,...,...,...,...,...
9989,OD9990,Sudeep,"Eggs, Meat & Fish",Eggs,Madurai,12/24/2015,West,945,0.16,359.10,Tamil Nadu
9990,OD9991,Alan,Bakery,Biscuits,Kanyakumari,07-12-2015,West,1195,0.26,71.70,Tamil Nadu
9991,OD9992,Ravi,Food Grains,Rice,Bodi,06-06-2017,West,1567,0.16,501.44,Tamil Nadu
9992,OD9993,Peer,Oil & Masala,Spices,Pudukottai,10/16/2018,West,1659,0.15,597.24,Tamil Nadu
9993,OD9994,Ganesh,Food Grains,Atta & Flour,Tirunelveli,4/17/2018,West,1034,0.28,165.44,Tamil Nadu

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Customer Name  9994 non-null   object
 2   Category       9994 non-null   object
 3   Sub Category   9994 non-null   object
 4   City           9994 non-null   object
 5   Order Date     9994 non-null   object
 6   Region         9994 non-null   object
 7   Sales          9994 non-null   int64
 8   Discount       9994 non-null   float64
 9   Profit         9994 non-null   float64
 10  State          9994 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 859.0+ KB

In [5]:
data.nunique()

Order ID         9994
Customer Name      50
Category            7
Sub Category       23
City               24
Order Date       1236
Region              5
Sales            1989
Discount           26
Profit           8380
State               1
dtype: int64

In [6]:
data = data.drop(['Order ID', "State"], axis=1)

In [7]:
data

,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit
0,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,North,1254,0.12,401.28
1,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,South,749,0.18,149.80
2,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,West,2360,0.21,165.20
3,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,South,896,0.25,89.60
4,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,South,2355,0.26,918.45
...,...,...,...,...,...,...,...,...,...
9989,Sudeep,"Eggs, Meat & Fish",Eggs,Madurai,12/24/2015,West,945,0.16,359.10
9990,Alan,Bakery,Biscuits,Kanyakumari,07-12-2015,West,1195,0.26,71.70
9991,Ravi,Food Grains,Rice,Bodi,06-06-2017,West,1567,0.16,501.44
9992,Peer,Oil & Masala,Spices,Pudukottai,10/16/2018,West,1659,0.15,597.24
9993,Ganesh,Food Grains,Atta & Flour,Tirunelveli,4/17/2018,West,1034,0.28,165.44

In [8]:
data['Category'].unique()

array(['Oil & Masala', 'Beverages', 'Food Grains', 'Fruits & Veggies',
       'Bakery', 'Snacks', 'Eggs, Meat & Fish'], dtype=object)

In [9]:
data['Order Date'].unique()

array(['11-08-2017', '06-12-2017', '10-11-2016', ..., '3/16/2015',
       '8/29/2016', '04-06-2017'], dtype=object)

In [10]:
data.columns = data.columns.str.replace(' ', '_') # Replacing the space(s) in the colunm names with underscore(_)
data

,Customer_Name,Category,Sub_Category,City,Order_Date,Region,Sales,Discount,Profit
0,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,North,1254,0.12,401.28
1,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,South,749,0.18,149.80
2,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,West,2360,0.21,165.20
3,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,South,896,0.25,89.60
4,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,South,2355,0.26,918.45
...,...,...,...,...,...,...,...,...,...
9989,Sudeep,"Eggs, Meat & Fish",Eggs,Madurai,12/24/2015,West,945,0.16,359.10
9990,Alan,Bakery,Biscuits,Kanyakumari,07-12-2015,West,1195,0.26,71.70
9991,Ravi,Food Grains,Rice,Bodi,06-06-2017,West,1567,0.16,501.44
9992,Peer,Oil & Masala,Spices,Pudukottai,10/16/2018,West,1659,0.15,597.24
9993,Ganesh,Food Grains,Atta & Flour,Tirunelveli,4/17/2018,West,1034,0.28,165.44

In [11]:
searchfor = ['/']
data[data.Order_Date.str.contains('|'.join(searchfor))]

,Customer_Name,Category,Sub_Category,City,Order_Date,Region,Sales,Discount,Profit
12,Sharon,Snacks,Cookies,Dindigul,4/15/2018,South,1659,0.19,315.21
14,Sundar,"Eggs, Meat & Fish",Chicken,Kanyakumari,11/22/2016,Central,831,0.22,207.75
15,Ramesh,Oil & Masala,Edible Oil & Ghee,Krishnagiri,11/22/2016,Central,1440,0.11,100.80
17,Arutra,Beverages,Health Drinks,Bodi,5/13/2015,West,1617,0.19,113.19
18,Haseena,"Eggs, Meat & Fish",Mutton,Tenkasi,8/27/2015,West,1757,0.35,386.54
...,...,...,...,...,...,...,...,...,...
9985,Shree,"Eggs, Meat & Fish",Mutton,Kanyakumari,11/13/2016,West,1286,0.30,475.82
9987,Ganesh,Fruits & Veggies,Fresh Vegetables,Theni,10/19/2015,West,1350,0.15,67.50
9989,Sudeep,"Eggs, Meat & Fish",Eggs,Madurai,12/24/2015,West,945,0.16,359.10
9992,Peer,Oil & Masala,Spices,Pudukottai,10/16/2018,West,1659,0.15,597.24
9993,Ganesh,Food Grains,Atta & Flour,Tirunelveli,4/17/2018,West,1034,0.28,165.44

In [12]:
data['Order_Date'] = pd.to_datetime(data['Order_Date'], format='mixed')

data['Order_Date'] = data['Order_Date'].dt.strftime('%d-%m-%Y')

print(data)

     Customer_Name           Category      Sub_Category         City  \
0           Harish       Oil & Masala           Masalas      Vellore
1            Sudha          Beverages     Health Drinks  Krishnagiri
2          Hussain        Food Grains      Atta & Flour   Perambalur
3          Jackson   Fruits & Veggies  Fresh Vegetables   Dharmapuri
4          Ridhesh        Food Grains   Organic Staples         Ooty
...            ...                ...               ...          ...
9989        Sudeep  Eggs, Meat & Fish              Eggs      Madurai
9990          Alan             Bakery          Biscuits  Kanyakumari
9991          Ravi        Food Grains              Rice         Bodi
9992          Peer       Oil & Masala            Spices   Pudukottai
9993        Ganesh        Food Grains      Atta & Flour  Tirunelveli

      Order_Date Region  Sales  Discount  Profit
0     08-11-2017  North   1254      0.12  401.28
1     08-11-2017  South    749      0.18  149.80
2     12-06-2017   West   2360      0.21  165.20
3     11-10-2016  South    896      0.25   89.60
4     11-10-2016  South   2355      0.26  918.45
...          ...    ...    ...       ...     ...
9989  24-12-2015   West    945      0.16  359.10
9990  12-07-2015   West   1195      0.26   71.70
9991  06-06-2017   West   1567      0.16  501.44
9992  16-10-2018   West   1659      0.15  597.24
9993  17-04-2018   West   1034      0.28  165.44

[9994 rows x 9 columns]

In [13]:
data['Order_Date'].unique()

array(['08-11-2017', '12-06-2017', '11-10-2016', ..., '16-03-2015',
       '29-08-2016', '06-04-2017'], dtype=object)

In [14]:
#Converting a timestamp colunm into string so we can extract 'Year as Yr', 'Month as Mth', 'Date as Dy'

df=data['Order_Date'].astype(str)

#extract 'Year as Yr', 'Month as Mth', 'Date as Dy'

data['Dy'] = df.apply(lambda x: x.split("-")[0])
data['Mth'] = df.apply(lambda x: x.split("-")[1])
data['Yr'] = df.apply(lambda x: x.split("-")[2])

#print our new data
data

,Customer_Name,Category,Sub_Category,City,Order_Date,Region,Sales,Discount,Profit,Dy,Mth,Yr
0,Harish,Oil & Masala,Masalas,Vellore,08-11-2017,North,1254,0.12,401.28,08,11,2017
1,Sudha,Beverages,Health Drinks,Krishnagiri,08-11-2017,South,749,0.18,149.80,08,11,2017
2,Hussain,Food Grains,Atta & Flour,Perambalur,12-06-2017,West,2360,0.21,165.20,12,06,2017
3,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,11-10-2016,South,896,0.25,89.60,11,10,2016
4,Ridhesh,Food Grains,Organic Staples,Ooty,11-10-2016,South,2355,0.26,918.45,11,10,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Sudeep,"Eggs, Meat & Fish",Eggs,Madurai,24-12-2015,West,945,0.16,359.10,24,12,2015
9990,Alan,Bakery,Biscuits,Kanyakumari,12-07-2015,West,1195,0.26,71.70,12,07,2015
9991,Ravi,Food Grains,Rice,Bodi,06-06-2017,West,1567,0.16,501.44,06,06,2017
9992,Peer,Oil & Masala,Spices,Pudukottai,16-10-2018,West,1659,0.15,597.24,16,10,2018
9993,Ganesh,Food Grains,Atta & Flour,Tirunelveli,17-04-2018,West,1034,0.28,165.44,17,04,2018

In [15]:
data = data.drop(['Order_Date'],axis=1)

In [16]:
data

,Customer_Name,Category,Sub_Category,City,Region,Sales,Discount,Profit,Dy,Mth,Yr
0,Harish,Oil & Masala,Masalas,Vellore,North,1254,0.12,401.28,08,11,2017
1,Sudha,Beverages,Health Drinks,Krishnagiri,South,749,0.18,149.80,08,11,2017
2,Hussain,Food Grains,Atta & Flour,Perambalur,West,2360,0.21,165.20,12,06,2017
3,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,South,896,0.25,89.60,11,10,2016
4,Ridhesh,Food Grains,Organic Staples,Ooty,South,2355,0.26,918.45,11,10,2016
...,...,...,...,...,...,...,...,...,...,...,...
9989,Sudeep,"Eggs, Meat & Fish",Eggs,Madurai,West,945,0.16,359.10,24,12,2015
9990,Alan,Bakery,Biscuits,Kanyakumari,West,1195,0.26,71.70,12,07,2015
9991,Ravi,Food Grains,Rice,Bodi,West,1567,0.16,501.44,06,06,2017
9992,Peer,Oil & Masala,Spices,Pudukottai,West,1659,0.15,597.24,16,10,2018
9993,Ganesh,Food Grains,Atta & Flour,Tirunelveli,West,1034,0.28,165.44,17,04,2018

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_Name  9994 non-null   object
 1   Category       9994 non-null   object
 2   Sub_Category   9994 non-null   object
 3   City           9994 non-null   object
 4   Region         9994 non-null   object
 5   Sales          9994 non-null   int64
 6   Discount       9994 non-null   float64
 7   Profit         9994 non-null   float64
 8   Dy             9994 non-null   object
 9   Mth            9994 non-null   object
 10  Yr             9994 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 859.0+ KB